apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrahub.fullname" . }}-postgres
  labels:
    {{- include "infrahub.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  selector:
    {{- include "infrahub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
