apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrahub.fullname" . }}-redis
  labels:
    {{- include "infrahub.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "infrahub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
