apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infrahub.fullname" . }}-nginx-config
  labels:
    {{- include "infrahub.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
data:
  default.conf: |-
{{ .Files.Get "files/nginx-default.conf" | indent 4 }}
